@startuml
class Posts {
    id 
    ..
    id_active
    ..
    id_comment
    ..
    date
    ..
    content
}

note left of Posts
Вся информация о посте: 
акивность на нем, 
комментарии, дата 
и контент поста
end note

class Comments {
    id
    ..
    id_user
    ..
    date
    ..
    text_comment
    ..
    id_answered_comment
}

note bottom of Comments
Комментарии оставленные
пользователем вместе с
датой и ссылкой на 
ответный комментарий
если это необходимо
end note

class Active {
    id
    ..
    type (like / see)
    ..
    id_user
    ..
    date
    ..
    time
}

note bottom of Active
Проявление активности 
(лайк / просмотр) от 
какого-то человека
вместе с датой и 
временем
end note

class WallUsers {
    id_user
    ..
    id_post
}

note left of WallUsers
Стена постов от 
каждого пользователя
end note

WallUsers::id_post --> Posts

Posts::id_comment --> Comments
Posts::list_likes --> Active



' Kafka --> Posts #green;line.dotted;text:green : info о посте 
' Kafka --> Comments #green;line.dotted;text:green : info о комментарии
' Kafka --> Likes #green;line.dotted;text:green : info о лайке







@enduml