@startuml


package "Analytics Service" <<Rectangle>> {
    


class UserStat {
    id :: SIZE_T
    ..
    id_user :: SIZE_T
    ..
    number_posts :: SIZE_T
    ..
    number_friends :: SIZE_T
    ..
    last_online :: STRING
}

note bottom of UserStat
Статистика, которую 
можно собрать у клиента
end note


class PostStat {
    id :: SIZE_T
    ..
    id_post :: SIZE_T
    ..
    number_likes :: SIZE_T
    ..
    number_comments :: SIZE_T
    ..
    number_seeing :: SIZE_T
    ..
    data_last_update :: SIZE_T
}

note bottom of PostStat
Статистика, которую 
можно собрать у поста
end note

class Active {
    id :: SIZE_T
    ..
    type (like / see) :: STRING
    ..
    id_user :: SIZE_T
    ..
    date :: STRING
    ..
    id_posts :: SIZE_T
    ..
    friend (yes/no) :: STRING
}

note bottom of Active
Проявление активности 
(лайк / просмотр) от 
какого-то человека
вместе с датой и 
временем
end note

}

@enduml


' Option + D