@startuml


class UserStat {
    id
    ..
    id_user
    ..
    number_posts
    ..
    last_activity
    ..
    last_online
}

note top of UserStat
Статистика, которую 
можно собрать у клиента
end note


class PostStat {
    id
    ..
    id_post
    ..
    number_likes
    ..
    number_comments
    ..
    number_seeing
    ..
    data_last_update
    ..
    type_content
    ..
    id_active_stat
}

note top of PostStat
Статистика, которую 
можно собрать у поста
end note

class ActiveStat {
    id
    ..
    id_user
    ..
    id_active
    ..
    type
    ..
    friend (yes/no)
    ..
    last_update
}

note left of ActiveStat
Статистика, которую 
можно собрать у
активности поста
end note


PostStat::id_active_stat --> ActiveStat

@enduml


' Option + D