version: '3'

services:
    api:
        build: 
            context: api  
        environment:
            API_SERVER_URL: "http://api:8090"
            USERSERVICE_SERVER_URL: "http://userservice:8091"
        # command: ["--private", "/signature.pem", "--public", "/signature.pub", "--port", "8090"]
        ports:
            - 8090:8090
        depends_on:
            - userservice
        networks:
            - social-network

    userservice:
        build: 
            context: userservice
        # environment:
        #     - FLASK_ENV=development
        ports:
            - 8091:8091
        networks:
            - social-network
        depends_on:
            - database


    database:
        # hostname: postgres
        image: postgres:12

        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: user_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - social-network

    tests:
        build:
            context: tests
        environment:
            API_SERVER_URL: "http://api:8090"
            USERSERVICE_SERVER_URL: "http://userservice:8091"
        networks:
            - social-network

        depends_on:
            - api
            - userservice


volumes:
    postgres_data:

networks:
    social-network: