version: '3'

services:
    api:
        build: 
            context: .
            dockerfile: api/Dockerfile 
        environment:
            API_SERVER_URL: "http://api:8090"
            USERSERVICE_SERVER_URL: "http://userservice:8091"
            POST_SERVER_URL: "http://post_server:50051"
            # - PYTHONPATH=/docs
        # environment:
            PYTHONPATH : '/docs'
            POST_SERVER_HOST : post_server
            POST_SERVER_ADDR : post_server:50051
        ports:
            - 8090:8090
        depends_on:
            - userservice
            - proto
            - post_server
        networks:
            - social-network

    userservice:
        build: 
            context: userservice
        # environment:
        #     - FLASK_ENV=development
        ports:
            - 8091:8091
        networks:
            - social-network
        depends_on:
            - database

    post_server:
        build: 
            context: .
            dockerfile: post_server/Dockerfile 
        ports:
            - "50051:50051"
        networks:
            - social-network
        depends_on:
            - database
            - proto

    proto:
        build:
            context: .
            dockerfile: proto/Dockerfile 
        environment:
            PYTHONPATH : '/docs'
        networks:
            - social-network
        volumes:
            - ./proto:/docs/proto


    database:
        # hostname: postgres
        image: postgres:12

        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: user_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - social-network

    tests:
        build:
            context: tests
        environment:
            API_SERVER_URL: "http://api:8090"
            USERSERVICE_SERVER_URL: "http://userservice:8091"
        networks:
            - social-network

        depends_on:
            - api
            - userservice


volumes:
    postgres_data:

networks:
    social-network: