@startuml

package "Post Service" <<Rectangle>> {
    

class Posts {
    id :: SIZE_T
    ..
    id_user :: SIZE_T
    ..
    date :: STRING
    ..
    content :: STRING
}

note bottom of Posts
Вся информация о посте: 
акивность на нем, 
комментарии, дата 
и контент поста
end note

class Comments {
    id :: SIZE_T
    ..
    id_user :: SIZE_T
    ..
    date ::STRING
    ..
    text_comment :: STRING
    ..
    parent_id :: SIZE_T
}

note bottom of Comments
Комментарии оставленные
пользователем вместе с
датой и ссылкой на 
ответный комментарий
если это необходимо
end note

}

package "User Service" <<Rectangle>> {
    

class Users {
    id :: SIZE_T
    ..
    id_user :: SIZE_T
    ..
    name :: STRING
    ..
    surname :: STRING
    ..
    phone :: STRING
    ..
    birthday :: STRING
    ..
    role :: STRING
    ..
    mail :: STRING
    ..
    status :: STRING
    ..
    token :: STRING
    ..
    updated_at :: DATE
}

note bottom of Users
Главная информация 
о пользователе, 
его имя, фамилия, 
роль и день рождения
end note


class Register {
    id :: SIZE_T
    ..
    login ::STRING
    ..
    password :: STRING
    ..
    mail :: STRING
    ..
    created_at :: DATA
}

note bottom of Register
Информация, необходимая
для регистрации
end note


class ListFrineds {
    id :: SIZE_T
    ..
    id_user :: SIZE_T
    ..
    frined :: SIZE_T
    ..
    name :: STRING
    ..
    surname :: STRING
}

note bottom of ListFrineds
Список друзей
end note

}

package "Analytics Service" <<Rectangle>> {
    


class UserStat {
    id :: SIZE_T
    ..
    id_user :: SIZE_T
    ..
    number_posts :: SIZE_T
    ..
    number_friends :: SIZE_T
    ..
    last_online :: STRING
}

note bottom of UserStat
Статистика, которую 
можно собрать у клиента
end note


class PostStat {
    id :: SIZE_T
    ..
    id_post :: SIZE_T
    ..
    number_likes :: SIZE_T
    ..
    number_comments :: SIZE_T
    ..
    number_seeing :: SIZE_T
    ..
    data_last_update :: SIZE_T
}

note bottom of PostStat
Статистика, которую 
можно собрать у поста
end note

class Active {
    id :: SIZE_T
    ..
    type (like / see) :: STRING
    ..
    id_user :: SIZE_T
    ..
    date :: STRING
    ..
    id_posts :: SIZE_T
    ..
    friend (yes/no) :: STRING
}

note bottom of Active
Проявление активности 
(лайк / просмотр) от 
какого-то человека
вместе с датой и 
временем
end note

}

Register::id_user -> Users::id_user #line.dotted
Posts::id_user -> Users::id_user #line.dotted
Comments::id_user -> Users::id_user #line.dotted
Comments::parent_id -> Comments::id #line.dotted
UserStat::id_user -> Users::id_user #line.dotted
PostStat::id_post -> Posts::id #line.dotted

@enduml