@startuml
package "User Service" <<Rectangle>> {
    

class Users {
    id :: SIZE_T
    ..
    id_user :: SIZE_T
    ..
    name :: STRING
    ..
    surname :: STRING
    ..
    phone :: STRING
    ..
    birthday :: STRING
    ..
    role :: STRING
    ..
    mail :: STRING
    ..
    status :: STRING
    ..
    token :: STRING
    ..
    updated_at :: DATE
}

note bottom of Users
Главная информация 
о пользователе, 
его имя, фамилия, 
роль и день рождения
end note


class Register {
    id :: SIZE_T
    ..
    login ::STRING
    ..
    password :: STRING
    ..
    mail :: STRING
    ..
    created_at :: DATA
}

note bottom of Register
Информация, необходимая
для регистрации
end note


class ListFrineds {
    id :: SIZE_T
    ..
    id_user :: SIZE_T
    ..
    frined :: SIZE_T
    ..
    name :: STRING
    ..
    surname :: STRING
}

note bottom of ListFrineds
Список друзей
end note

}

@enduml