@startuml
class Users {
    id_user
    ..
    name
    ..
    surname 
    ..
    birthday
    ..
    role 
}

note right of Users
Главная информация 
о пользователе, 
его имя, фамилия, 
роль и день рождения
end note


class Register {
    email
    ..
    password
    ..
    sha_key (private)
    ..
    sha-key (public)
    ..
    id_user
}

note right of Register
Информация, необходимая
для регистрации
end note

class Activity {
    id_user
    ..
    id_stat 
    ..
    id_post_stat
    ..
    list_friends
    ..
    status
}

note left of Activity
Информация показывающая
активность и статистику
пользователя в социальной
сети
end note

class ListFrineds {
    id
    ..
    id_user
}

note left of ListFrineds
Список друзей
end note

Register::id_user --> Users

Users --> Activity
Users::id_user --> Activity::id_user  #line.dotted;

Activity::list_friends --> ListFrineds

@enduml